### ISSUE TITLE
Foundry V11 Support?

### ISSUE THREAD

**Issue by Stormthirst** [stschoelzel/My-Shared-Compendia#11]
Is this project still alive? I do hope so, because it's super useful!

**Comment by stschoelzel** [comment]
I'm on a game break over the summer, so I wasn't aware that foundry 11 released.
I'll take a lock soon...

**Comment by Stormthirst** [comment]
No worries! Nothing urgent I don't think. Seems to be working ok. 

Would be nice to be able to configure it within the game

**Comment by stschoelzel** [comment]
Just tested it, it seems to work like a charm?

Is it just the "Compatibility Risk" Warning?

An "in game config" might be above my skill - but its a poject :D

**Comment by Stormthirst** [comment]
Yes - just a compatibility risk warning. Seems to be behaving itself.

Thanks for all your work!

**Comment by stschoelzel** [comment]
For a quick fix; /module.json, Line 16, 10->11 :)
