### ISSUE TITLE
My shared Compendia not working with v10?

### ISSUE THREAD

**Issue by Cempres** [stschoelzel/My-Shared-Compendia#3]
Title says it all, I'm having a hard time finding any information regarding if there's a fix or not to this issue.

**Comment by livefast9986** [comment]
There is a fix. Because of changes in V10 of Foundry you have to add a line of code "system": "dnd5e" in each bracket. see below image

![image](https://user-images.githubusercontent.com/100723823/191380528-0b32c794-7454-42b3-990e-909ee14bb23a.png)

**Comment by stschoelzel** [comment]
I'll update it - thanks for the info!
