### ISSUE TITLE
No way to use in v10 without dnd5e

### ISSUE THREAD

**Issue by ryzimmer** [stschoelzel/My-Shared-Compendia#7]
I have been using this module for pbta games that I have been running. I have 3 games and like to reuse things like journals and actors across these games so was using this module to do this. V1.2 of this module does not show up in foundry v10 (it says its compatible on the foundry module info page, but the module list shows its only compatible with 9. When I try to use v1,2 the module does not show up in the list within the world. When I tried moving to v1.3, it would let me turn on the module, but none of the compendium showed up. 

For context this is the game system I'm using: https://foundryvtt.com/packages/pbta

**Comment by ryzimmer** [comment]
this is a limitation of foundry v10 :(

**Comment by stschoelzel** [comment]
Yes, it is :(
But you can ... and I just saw you already forked and fixed it yourself. Nice.

**Comment by ryzimmer** [comment]
Yeah my original plan was to just make the changes to the module itself and send you a PR with the changes to merge into main, but I didn’t have permissions to push changes to a new branch so I forked the module instead since that was the easiest solution. I looked into trying to make something generic the way it used to be, but the Foundry team said it wasn’t possible. I view that as a regression from v9 as there was functionality that no longer exists, but they don’t agree. It was pretty easy to edit your module to make it so thanks for making that easy. If you want me to add the PBTA support to your module, I can do that if you give me permissions. I don’t need access to the main branch, I usually just create a branch and then create a PR to merge to main that you should require your own approval on.

Ryan


On Oct 19, 2022, at 8:20 AM, stschoelzel ***@***.***> wrote:

﻿

Yes, it is :(
But you can ... and I just saw you already forked and fixed it yourself. Nice.
